# Generated by Django 3.2.9 on 2022-01-18 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_profile_image_profile_profile_image'),
        ('projects', '0009_review_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
